// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";
import $$Image from "next/image";

function AboutProfile$default(Props) {
  return React.createElement("section", {
              className: "flex flex-wrap w-full items-start justify-center"
            }, React.createElement($$Image, {
                  alt: "MiryangJung",
                  className: "rounded-lg",
                  objectFit: "cover",
                  src: "/about/about.jpg",
                  width: 300.0,
                  height: 300.0
                }), React.createElement("div", {
                  className: "min-w-[300px] max-w-[400px] px-5 break-words leading-6 mt-5 md:mt-0"
                }, "새로운 경험을 좋아하는 개발자입니다.", React.createElement("br", undefined), React.createElement("br", undefined), "최신 트렌드와 명료한 코드를 작성하는 것에 관심이 많으며, 정보를 공유하는 것에 기쁨을\n        느낍니다.", React.createElement("br", undefined), "보안을 했고, 요즘은 프론트엔드에 힘을 쏟고 있습니다.", React.createElement("br", undefined), React.createElement("br", undefined), "여행을 좋아합니다. 현재까지 다녀온 나라", React.createElement("br", undefined), React.createElement("span", {
                      className: "text-gray-600"
                    }, "Denmark, Turkey, Finland, Sweden, Norway, Italy, United Kingdom, Czechia, Hungary,\n        Austria, Switzerland, France, Japan, Philippines, Taiwan"), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement(Link, {
                      children: React.createElement("button", {
                            className: "px-7 py-2 bg-blue-700 font-semibold border-none outline-none rounded-xl cursor-pointer"
                          }, "Resume"),
                      href: "/resume",
                      passHref: true
                    })));
}

var $$default = AboutProfile$default;

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
