// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function ChatBubble$default(Props) {
  var content = Props.content;
  var color = Props.color;
  return React.createElement("div", {
              className: "ml-auto py-2 px-2.5 break-all leading-6 rounded-[10px] rounded-br-none font-light mt-2.5 max-w-[90%] text-[var(--tx-white)]",
              style: {
                background: color
              }
            }, content);
}

var $$default = ChatBubble$default;

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
