// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Metadata from "../data/Metadata.bs.js";
import Script from "next/script";

function GA$default(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(Script, {
                  src: "https://www.googletagmanager.com/gtag/js?id=" + Metadata.analytics.google,
                  strategy: "lazyOnload"
                }), React.createElement(Script, {
                  src: "\n            window.dataLayer = window.dataLayer || [];\n            function gtag(){dataLayer.push(arguments);}\n            gtag('js', new Date());\n            gtag('config', '" + Metadata.analytics.google + "');\n        ",
                  strategy: "lazyOnload"
                }));
}

var $$default = GA$default;

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
