// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function GuestbookDate$default(Props) {
  var date = Props.date;
  return React.createElement("div", {
              className: "text-xs text-[var(--tx-sub-dark)] w-full text-center mt-2.5"
            }, date);
}

var $$default = GuestbookDate$default;

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
