// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function GuestbookNotice$default(Props) {
  return React.createElement("div", {
              className: "text-sm text-[var(--tx-main)] mb-5 w-full text-left"
            }, "악플 방지를 위해 방명록 등록 시 IP를 수집합니다.", React.createElement("br", undefined), "이에 동의하시는 분만 방명록을 작성해 주시기 바랍니다.");
}

var $$default = GuestbookNotice$default;

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
