// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function RecentPost$default(Props) {
  var posts = Props.posts;
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "w-full font-bold text-[35px] mt-12"
                }, "Recent Post"), Belt_Array.map(posts, (function (post) {
                    return React.createElement(Link, {
                                children: React.createElement("div", {
                                      className: "w-full flex flex-col flex-nowrap cursor-pointer m-1.5"
                                    }, React.createElement("span", {
                                          className: "font-medium text-xl mt-5"
                                        }, post.title), React.createElement("span", {
                                          className: "mt-1.5 text-[ var(--tx-sub-dark)]"
                                        }, post.description)),
                                href: "/blog/" + post.slug,
                                passHref: true,
                                key: post.slug
                              });
                  })));
}

var $$default = RecentPost$default;

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
