// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function ResumeTitle$default(Props) {
  var title = Props.title;
  return React.createElement("div", {
              className: "w-full mt-[50px] mb-2.5 text-[22px] text-gray-500 font-semibold"
            }, title);
}

var $$default = ResumeTitle$default;

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
