// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function defalut(title) {
  return React.createElement("div", {
              className: "w-full mt-[50px] mb-2.5 text-[22px] text-gray-500 font-semibold"
            }, title);
}

export {
  defalut ,
  
}
/* react Not a pure module */
