// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Search$default(Props) {
  var changeHandler = Props.changeHandler;
  return React.createElement("div", {
              className: "w-full flex flex-nowrap items-center py-2.5 px-5 rounded-[20px] border-2 border-solid border-[var(--bg-main)] bg-[var(--bg-sub)] mb-8 hover:border-[ var(--tx-accent-light)]"
            }, React.createElement("input", {
                  className: "appearance-none bg-transparent flex-1 outline-none",
                  placeholder: "Search...",
                  type: "text",
                  onChange: changeHandler
                }), React.createElement("svg", {
                  height: "24px",
                  width: "24px",
                  fill: "#B7BAB6",
                  viewBox: "0 0 24 24",
                  xmlns: "http://www.w3.org/2000/svg"
                }, React.createElement("path", {
                      d: "M0 0h24v24H0z",
                      fill: "none"
                    }), React.createElement("path", {
                      d: "M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"
                    })));
}

var $$default = Search$default;

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
