// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Title$defalut(Props) {
  var title = Props.title;
  var des = Props.des;
  return React.createElement("div", {
              className: "flex flex-col flex-nowrap pb-5 w-full"
            }, React.createElement("span", {
                  className: "text-[50px] font-extrabold color bg-clip-text ",
                  style: {
                    background: "linear-gradient(to right, var(--tx-accent-light), var(--tx-accent), var(--tx-sub))",
                    color: "rgba(0, 0, 0, 0)",
                    backgroundSize: "200% 200%",
                    animation: "rainbow 2s ease-in-out infinite",
                    transition: "color 0.2s ease-in-out"
                  }
                }, title), React.createElement("span", {
                  className: "text-lg font-light color-[var(--tx-sub-dark)] break-all mt-2.5"
                }, des));
}

var defalut = Title$defalut;

export {
  defalut ,
  
}
/* react Not a pure module */
